name: Upload builds to release

on:
  workflow_dispatch: 
  release: 
    types: [released]

jobs:
  build-win: 
    name: Build and upload amd64 exe
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - uses: iffy/install-nim@v5
      - name: Build exe
        run: |
          nimble install -d -y
          nimble build

      - uses: oprypin/find-latest-tag@v1
        id: latest-tag  # The step ID to refer to later.
        with:
          repository: ${{ github.repository }}  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
    
      - name: Upload exe
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.exe"
          file_glob: true
          tag: ${{ steps.latest-tag.outputs.tag }}
          overwrite: true
